version: "3"

services:
  bet1:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: SimpleTrader/Dockerfile
    env_file: .env
    environment:
      UNIQUE_ID: 2210152300
      CRYPTO_TICKER: btc
      TYPE: long
      INITIAL_PRICE_USD: 19000
      THRESHOLD_PERCENT: 5
      PRICE_CHECK_INTERVAL: 38min
      LONG_FIAT_AMOUNT_SHORT_CRYPTO_AMOUNT: 10
      
# Volumes to save in 2210152300.json file the smallest/biggest price and if it's closed or not
# FOR CLOSING IT SHOULD save what were parameters and approximately profit/loss in crypto or usd
# DO NOT START AGAIN ALREADY CLOSED BETS!