version: "3"

services:
  simple-trader:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: SimpleTrader/Dockerfile
    env_file: .env
    volumes:
      - /var/simple-trader:/var/simple-trader
#    environment:
#      UNIQUE_ID: 2210152300
#      CRYPTO_TICKER: xbt
#      TYPE: long
#      INITIAL_PRICE_USD: 19000
#      THRESHOLD_PERCENT: 1
#      PRICE_CHECK_INTERVAL: 1m
#      CRYPTO_AMOUNT: 10