version: "3"

services:
  bet1:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: SimpleTrader/Dockerfile
    env_file: .env
    environment:
      CRYPTO_TICKER: btc
      TYPE: long
      INITIAL_PRICE_USD: 19000
      THRESHOLD_PERCENT: 5
      LONG_FIAT_AMOUNT_SHORT_CRYPTO_AMOUNT: 10