version: "3"

services:
  bet1:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: SimpleTrader/Dockerfile
    env_file: .env
    environment:
      CURRENCY: btc
      INITIAL_PRICE: 19000
      TYPE: long
      THRESHOLD: 5
      FIAT_AMOUNT: 10